"""add user target role

Revision ID: 0add6bdb5c03
Revises: 80d0152fdbab
Create Date: 2026-08-14 00:33:09.816742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0add6bdb5c03'
down_revision: Union[str, Sequence[str], None] = '80d0152fdbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_role_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_role_updated_at')
    op.drop_column('users', 'target_role')
    # ### end Alembic commands ###
