"""add interview answer dimensions

Revision ID: 2e65cf1da8e1
Revises: 319ebdeb8386
Create Date: 2026-08-16 21:44:06.331638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e65cf1da8e1'
down_revision: Union[str, Sequence[str], None] = '319ebdeb8386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_answers', sa.Column('dimensions', sa.JSON(), nullable=True))
    op.add_column('interview_answers', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('interview_answers', sa.Column('improvements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_answers', 'improvements')
    op.drop_column('interview_answers', 'strengths')
    op.drop_column('interview_answers', 'dimensions')
    # ### end Alembic commands ###
