"""add skill gap details

Revision ID: 319ebdeb8386
Revises: 8a5d68c66fe4
Create Date: 2026-08-15 22:53:24.412234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319ebdeb8386'
down_revision: Union[str, Sequence[str], None] = '8a5d68c66fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gaps', sa.Column('skill_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gaps', 'skill_details')
    # ### end Alembic commands ###
