"""add roadmap tasks

Revision ID: 8a5d68c66fe4
Revises: 0add6bdb5c03
Create Date: 2026-08-15 18:31:30.871028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5d68c66fe4'
down_revision: Union[str, Sequence[str], None] = '0add6bdb5c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roadmap_tasks_recommendation_id', 'roadmap_tasks', ['recommendation_id'], unique=False)
    op.create_index('ix_roadmap_tasks_user_id', 'roadmap_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roadmap_tasks_user_id', table_name='roadmap_tasks')
    op.drop_index('ix_roadmap_tasks_recommendation_id', table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    # ### end Alembic commands ###
