"""add resume version

Revision ID: ca6116dbeba4
Revises: 2e65cf1da8e1
Create Date: 2026-08-16 21:52:07.392186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6116dbeba4'
down_revision: Union[str, Sequence[str], None] = '2e65cf1da8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add per-user resume version numbers, backfilling existing rows.

    Added nullable first, then backfilled by upload order per user, then made
    NOT NULL. Adding it NOT NULL in one step would fail on any existing row.
    """
    op.add_column('resumes', sa.Column('version', sa.Integer(), nullable=True))

    # Number each user's resumes 1..n by upload time, oldest first.
    op.execute("""
        UPDATE resumes AS r
        SET version = numbered.rn
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY user_id ORDER BY uploaded_at, id
                   ) AS rn
            FROM resumes
        ) AS numbered
        WHERE r.id = numbered.id
    """)

    op.execute("UPDATE resumes SET version = 1 WHERE version IS NULL")
    op.alter_column('resumes', 'version', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'version')
    # ### end Alembic commands ###
